<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.example.org/IniciarConsultaEstadisticasGlobales/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="IniciarConsultaEstadisticasGlobales" targetNamespace="http://www.example.org/IniciarConsultaEstadisticasGlobales/">
  <wsdl:types>
    <xsd:schema targetNamespace="http://www.example.org/IniciarConsultaEstadisticasGlobales/">
      <xsd:element name="iniciar">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="WSKey" type="xsd:string"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="iniciarResponse">
        <xsd:complexType>
          <xsd:sequence>
          	<xsd:element name="datosEntrada"
          		type="tns:EstadisticasGlobalesType" />
          	<xsd:element name="mensajeSalida" type="xsd:string"></xsd:element>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    
      <xsd:complexType name="EstadisticasGlobalesType">
      	<xsd:sequence>
      		<xsd:element name="fechaInicio" type="xsd:dateTime"></xsd:element>
      		<xsd:element name="fechaFin" type="xsd:dateTime"></xsd:element>
      		<xsd:element name="numeroTotalFacturasEmitidas"
      			type="xsd:int">
      		</xsd:element>
      		<xsd:element name="sumaTotalImportes" type="xsd:double"></xsd:element>
      		<xsd:element name="numeroTotalFacturasValidas"
      			type="xsd:int">
      		</xsd:element>
      		<xsd:element name="numeroTotalFacturasSubsanadas"
      			type="xsd:int">
      		</xsd:element>
      		<xsd:element name="numeroTotalFacturasAnuladas"
      			type="xsd:int">
      		</xsd:element>
      		<xsd:element name="numeroTotalFacturasInvalidas"
      			type="xsd:int">
      		</xsd:element>
      		<xsd:element name="numeroTotalReportesCreados" type="xsd:int"></xsd:element>
      	</xsd:sequence>
      </xsd:complexType>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="iniciarRequest">
    <wsdl:part element="tns:iniciar" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="iniciarResponse">
    <wsdl:part element="tns:iniciarResponse" name="parameters"/>
  </wsdl:message>
  <wsdl:portType name="IniciarConsultaEstadisticasGlobales">
    <wsdl:documentation>Servicio iniciador de la composición del proceso de negocio de estadísticas</wsdl:documentation>
    <wsdl:operation name="iniciar">
      <wsdl:input message="tns:iniciarRequest"/>
      <wsdl:output message="tns:iniciarResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="IniciarConsultaEstadisticasGlobalesSOAP" type="tns:IniciarConsultaEstadisticasGlobales">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="iniciar">
      <soap:operation soapAction="http://www.example.org/IniciarConsultaEstadisticasGlobales/iniciar"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="IniciarConsultaEstadisticasGlobales">
    <wsdl:port binding="tns:IniciarConsultaEstadisticasGlobalesSOAP" name="IniciarConsultaEstadisticasGlobalesSOAP">
      <soap:address location="http://www.example.org/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
